/**
 * AUDITORIA
 * # Introducão  Seja bem-vindo a documentação da API do [SCANVIN](https://scanvin.com.br) para auditorias    Nossa API foi criada utilizando o padrão [REST](https://restfulapi.net/) e [HATEOAS](https://restfulapi.net/hateoas/), possibilitando a integração de seu sistema ao nosso, e está documentada abaixo.  # Como usar a API?  Logo a seguir você encontrará todos os recursos e métodos suportados pela API, sendo que essa página possibilita que você teste os recursos e métodos diretamente através dela.  # Autenticação  Você precisa de uma [API KEY](https://en.wikipedia.org/wiki/Application_programming_interface_key#HTTP_APIs) para identificar a conta que está realizando solicitações para a API. Você pode obter seu token de autenticação no seu [Painel do Cliente](https://auditoria.scanvin.com.br/client/).  Insira seu token no campo que se encontra topo desta página para testar os métodos da API.  # Webhook  Você também deve configurar seu [Webhook](https://en.wikipedia.org/wiki/Webhook) no [Painel do Cliente](https://auditoria.scanvin.com.br/client/webhook). Quando os resultados da auditoria estiverem disponíveis, uma notificação será enviada para a URL informada, via [HTTP POST](https://en.wikipedia.org/wiki/POST_(HTTP)). A notificação possui ```Content-type``` do tipo ```application/json```. O [JSON](https://en.wikipedia.org/wiki/JSON) postado contém um único campo, ```notification_id```, que contém o identificador único do evento que gerou a notificação. Deve-se então chamar o endpoint ```Inspection - Get Inspection```, informando esse mesmo identificador único, para recuperar os dados da vistoria, e da auditoria realizada.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Compliance model module.
* @module model/Compliance
* @version 1.0
*/
export default class Compliance {
    /**
    * Constructs a new <code>Compliance</code>.
    * @alias module:model/Compliance
    * @class
    * @param engine {Boolean} Informa se o número do motor está dentro dos padrões.
    * @param frontPlate {Boolean} Informa se a placa dianteira está dentro dos padrões.
    * @param rearPlate {Boolean} Informa se a placa traseira está dentro dos padrões.
    * @param vin {Boolean} Informa se o número do chassi está dentro dos padrões.
    */

    constructor(engine, frontPlate, rearPlate, vin) {
        
        
        this['engine'] = engine;
        this['front_plate'] = frontPlate;
        this['rear_plate'] = rearPlate;
        this['vin'] = vin;
        
    }

    /**
    * Constructs a <code>Compliance</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Compliance} obj Optional instance to populate.
    * @return {module:model/Compliance} The populated <code>Compliance</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Compliance();
                        
            
            if (data.hasOwnProperty('engine')) {
                obj['engine'] = ApiClient.convertToType(data['engine'], 'Boolean');
            }
            if (data.hasOwnProperty('front_plate')) {
                obj['front_plate'] = ApiClient.convertToType(data['front_plate'], 'Boolean');
            }
            if (data.hasOwnProperty('rear_plate')) {
                obj['rear_plate'] = ApiClient.convertToType(data['rear_plate'], 'Boolean');
            }
            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiClient.convertToType(data['vin'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * Informa se o número do motor está dentro dos padrões.
    * @member {Boolean} engine
    */
    engine = undefined;
    /**
    * Informa se a placa dianteira está dentro dos padrões.
    * @member {Boolean} front_plate
    */
    front_plate = undefined;
    /**
    * Informa se a placa traseira está dentro dos padrões.
    * @member {Boolean} rear_plate
    */
    rear_plate = undefined;
    /**
    * Informa se o número do chassi está dentro dos padrões.
    * @member {Boolean} vin
    */
    vin = undefined;




}
