/**
 * AUDITORIA
 * # Introducão  Seja bem-vindo a documentação da API do [SCANVIN](https://scanvin.com.br) para auditorias    Nossa API foi criada utilizando o padrão [REST](https://restfulapi.net/) e [HATEOAS](https://restfulapi.net/hateoas/), possibilitando a integração de seu sistema ao nosso, e está documentada abaixo.  # Como usar a API?  Logo a seguir você encontrará todos os recursos e métodos suportados pela API, sendo que essa página possibilita que você teste os recursos e métodos diretamente através dela.  # Autenticação  Você precisa de uma [API KEY](https://en.wikipedia.org/wiki/Application_programming_interface_key#HTTP_APIs) para identificar a conta que está realizando solicitações para a API. Você pode obter seu token de autenticação no seu [Painel do Cliente](https://auditoria.scanvin.com.br/client/).  Insira seu token no campo que se encontra topo desta página para testar os métodos da API.  # Webhook  Você também deve configurar seu [Webhook](https://en.wikipedia.org/wiki/Webhook) no [Painel do Cliente](https://auditoria.scanvin.com.br/client/webhook). Quando os resultados da auditoria estiverem disponíveis, uma notificação será enviada para a URL informada, via [HTTP POST](https://en.wikipedia.org/wiki/POST_(HTTP)). A notificação possui ```Content-type``` do tipo ```application/json```. O [JSON](https://en.wikipedia.org/wiki/JSON) postado contém um único campo, ```notification_id```, que contém o identificador único do evento que gerou a notificação. Deve-se então chamar o endpoint ```Inspection - Get Inspection```, informando esse mesmo identificador único, para recuperar os dados da vistoria, e da auditoria realizada.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Details model module.
* @module model/Details
* @version 1.0
*/
export default class Details {
    /**
    * Constructs a new <code>Details</code>.
    * @alias module:model/Details
    * @class
    * @param auditor {String} E-mail do auditor.
    * @param startedAt {String} Início da auditoria.
    * @param endedAt {String} Término da auditoria.
    */

    constructor(auditor, startedAt, endedAt) {
        
        
        this['auditor'] = auditor;
        this['started_at'] = startedAt;
        this['ended_at'] = endedAt;
        
    }

    /**
    * Constructs a <code>Details</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Details} obj Optional instance to populate.
    * @return {module:model/Details} The populated <code>Details</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Details();
                        
            
            if (data.hasOwnProperty('auditor')) {
                obj['auditor'] = ApiClient.convertToType(data['auditor'], 'String');
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'String');
            }
            if (data.hasOwnProperty('ended_at')) {
                obj['ended_at'] = ApiClient.convertToType(data['ended_at'], 'String');
            }
        }
        return obj;
    }

    /**
    * E-mail do auditor.
    * @member {String} auditor
    */
    auditor = undefined;
    /**
    * Início da auditoria.
    * @member {String} started_at
    */
    started_at = undefined;
    /**
    * Término da auditoria.
    * @member {String} ended_at
    */
    ended_at = undefined;




}
