/**
 * AUDITORIA
 * # Introducão  Seja bem-vindo a documentação da API do [SCANVIN](https://scanvin.com.br) para auditorias    Nossa API foi criada utilizando o padrão [REST](https://restfulapi.net/) e [HATEOAS](https://restfulapi.net/hateoas/), possibilitando a integração de seu sistema ao nosso, e está documentada abaixo.  # Como usar a API?  Logo a seguir você encontrará todos os recursos e métodos suportados pela API, sendo que essa página possibilita que você teste os recursos e métodos diretamente através dela.  # Autenticação  Você precisa de uma [API KEY](https://en.wikipedia.org/wiki/Application_programming_interface_key#HTTP_APIs) para identificar a conta que está realizando solicitações para a API. Você pode obter seu token de autenticação no seu [Painel do Cliente](https://auditoria.scanvin.com.br/client/).  Insira seu token no campo que se encontra topo desta página para testar os métodos da API.  # Webhook  Você também deve configurar seu [Webhook](https://en.wikipedia.org/wiki/Webhook) no [Painel do Cliente](https://auditoria.scanvin.com.br/client/webhook). Quando os resultados da auditoria estiverem disponíveis, uma notificação será enviada para a URL informada, via [HTTP POST](https://en.wikipedia.org/wiki/POST_(HTTP)). A notificação possui ```Content-type``` do tipo ```application/json```. O [JSON](https://en.wikipedia.org/wiki/JSON) postado contém um único campo, ```notification_id```, que contém o identificador único do evento que gerou a notificação. Deve-se então chamar o endpoint ```Inspection - Get Inspection```, informando esse mesmo identificador único, para recuperar os dados da vistoria, e da auditoria realizada.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Protocol from './Protocol';

/**
* The InspectionSubmit model module.
* @module model/InspectionSubmit
* @version 1.0
*/
export default class InspectionSubmit {
    /**
    * Constructs a new <code>InspectionSubmit</code>.
    * @alias module:model/InspectionSubmit
    * @class
    * @param status {Boolean} Informa se a requisição foi concluída com sucesso.
    * @param protocol {module:model/Protocol} 
    */

    constructor(status, protocol) {
        
        
        this['status'] = status;
        this['protocol'] = protocol;
        
    }

    /**
    * Constructs a <code>InspectionSubmit</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InspectionSubmit} obj Optional instance to populate.
    * @return {module:model/InspectionSubmit} The populated <code>InspectionSubmit</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InspectionSubmit();
                        
            
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Boolean');
            }
            if (data.hasOwnProperty('protocol')) {
                obj['protocol'] = Protocol.constructFromObject(data['protocol']);
            }
        }
        return obj;
    }

    /**
    * Informa se a requisição foi concluída com sucesso.
    * @member {Boolean} status
    */
    status = undefined;
    /**
    * @member {module:model/Protocol} protocol
    */
    protocol = undefined;




}
