/**
 * AUDITORIA
 * # Introducão  Seja bem-vindo a documentação da API do [SCANVIN](https://scanvin.com.br) para auditorias    Nossa API foi criada utilizando o padrão [REST](https://restfulapi.net/) e [HATEOAS](https://restfulapi.net/hateoas/), possibilitando a integração de seu sistema ao nosso, e está documentada abaixo.  # Como usar a API?  Logo a seguir você encontrará todos os recursos e métodos suportados pela API, sendo que essa página possibilita que você teste os recursos e métodos diretamente através dela.  # Autenticação  Você precisa de uma [API KEY](https://en.wikipedia.org/wiki/Application_programming_interface_key#HTTP_APIs) para identificar a conta que está realizando solicitações para a API. Você pode obter seu token de autenticação no seu [Painel do Cliente](https://auditoria.scanvin.com.br/client/).  Insira seu token no campo que se encontra topo desta página para testar os métodos da API.  # Webhook  Você também deve configurar seu [Webhook](https://en.wikipedia.org/wiki/Webhook) no [Painel do Cliente](https://auditoria.scanvin.com.br/client/webhook). Quando os resultados da auditoria estiverem disponíveis, uma notificação será enviada para a URL informada, via [HTTP POST](https://en.wikipedia.org/wiki/POST_(HTTP)). A notificação possui ```Content-type``` do tipo ```application/json```. O [JSON](https://en.wikipedia.org/wiki/JSON) postado contém um único campo, ```notification_id```, que contém o identificador único do evento que gerou a notificação. Deve-se então chamar o endpoint ```Inspection - Get Inspection```, informando esse mesmo identificador único, para recuperar os dados da vistoria, e da auditoria realizada.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Picture1 model module.
* @module model/Picture1
* @version 1.0
*/
export default class Picture1 {
    /**
    * Constructs a new <code>Picture1</code>.
    * @alias module:model/Picture1
    * @class
    * @param type {Number} Tipo da imagem. Os tipos disponíveis podem ser obtidos acessando o endpoint ```Inspection - Get Types```.
    * @param hash {String} Hash do arquivo da imagem.
    * @param pathOriginal {String} URL original da imagem, fornecida pelo cliente.
    * @param pathUpdated {String} URL da imagem editada, caso o auditor tenha decido realizar algum tipo de edição.
    * @param notes {String} Observações referentes à imagem, adicionadas pelo auditor.
    * @param bytes {Number} Tamanho em bytes do arquivo da imagem.
    * @param lat {String} Latitude em que a imagem foi fotografada.
    * @param lng {String} Longitude em que a imagem foi fotografada.
    */

    constructor(type, hash, pathOriginal, pathUpdated, notes, bytes, lat, lng) {
        
        
        this['type'] = type;
        this['hash'] = hash;
        this['path_original'] = pathOriginal;
        this['path_updated'] = pathUpdated;
        this['notes'] = notes;
        this['bytes'] = bytes;
        this['lat'] = lat;
        this['lng'] = lng;
        
    }

    /**
    * Constructs a <code>Picture1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Picture1} obj Optional instance to populate.
    * @return {module:model/Picture1} The populated <code>Picture1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Picture1();
                        
            
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
            if (data.hasOwnProperty('path_original')) {
                obj['path_original'] = ApiClient.convertToType(data['path_original'], 'String');
            }
            if (data.hasOwnProperty('path_updated')) {
                obj['path_updated'] = ApiClient.convertToType(data['path_updated'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('bytes')) {
                obj['bytes'] = ApiClient.convertToType(data['bytes'], 'Number');
            }
            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'String');
            }
            if (data.hasOwnProperty('lng')) {
                obj['lng'] = ApiClient.convertToType(data['lng'], 'String');
            }
        }
        return obj;
    }

    /**
    * Tipo da imagem. Os tipos disponíveis podem ser obtidos acessando o endpoint ```Inspection - Get Types```.
    * @member {Number} type
    */
    type = undefined;
    /**
    * Hash do arquivo da imagem.
    * @member {String} hash
    */
    hash = undefined;
    /**
    * URL original da imagem, fornecida pelo cliente.
    * @member {String} path_original
    */
    path_original = undefined;
    /**
    * URL da imagem editada, caso o auditor tenha decido realizar algum tipo de edição.
    * @member {String} path_updated
    */
    path_updated = undefined;
    /**
    * Observações referentes à imagem, adicionadas pelo auditor.
    * @member {String} notes
    */
    notes = undefined;
    /**
    * Tamanho em bytes do arquivo da imagem.
    * @member {Number} bytes
    */
    bytes = undefined;
    /**
    * Latitude em que a imagem foi fotografada.
    * @member {String} lat
    */
    lat = undefined;
    /**
    * Longitude em que a imagem foi fotografada.
    * @member {String} lng
    */
    lng = undefined;




}
